### ISSUE TITLE
Support YAML Format for Content Declaration Files

### ISSUE THREAD

**Issue by aymericzip** [aymericzip/intlayer#122]
# Support YAML Format for Content Declaration Files

## Current Behavior

Currently, Intlayer supports localized content stored in **JSON** or **TypeScript/JavaScript** declaration files with a structure like:

```bash
.
└── my-component
    ├── my-component.content.json
    └── my-component.tsx
```

or, for per-language:

```bash
.
└── my-component
    ├── my-component.content.json
    ├── my-component.content.fr.json
    └── my-component.tsx
```

JSON is the primary format used for both default and language-specific content files.

---

## Expected Behavior

We aim to **add support for YAML files** as a valid format for content declaration, with the following behavior:

- A default file can be written as:

```bash
.
└── my-component
    ├── my-component.content.yaml
    └── my-component.tsx
```

Example:

```yaml
# my-component.content.yaml
key: my-component
content:
  exampleOfContent:
    nodeType: translation
    translation:
      en: Example of returned error content in English
      fr: Exemple de contenu d'erreur renvoyé en français
      es: Ejemplo de contenido de error devuelto en español
```

- Per-language YAML files should also be supported:

```bash
.
└── my-component
    ├── my-component.content.fr.yaml
    └── my-component.tsx
```

Example:

```yaml
# my-component.content.fr.yaml
key: my-component
content:
  exampleOfContent:
    nodeType: translation
    translation: Exemple de contenu d'erreur renvoyé en français
```

### Key Points
- YAML should be supported **both for default files and per-locale files**.
- Developers can choose between JSON, TypeScript, or YAML based on preference.
- The structure and fallback logic remain identical.

---

## Motivation

- **Less verbose syntax**: YAML is more concise and readable compared to JSON.
- **Better integration with Ruby, Python, and other i18n ecosystems** where YAML is the standard.
- **Improved developer experience**: Some users prefer editing YAML over JSON.
- **Content reusability**: Easier to share content between different projects and stacks.
- **Aligns with user feedback** from Intlayer users looking for more flexible content management.

---

## Additional Considerations

- YAML parsing must **reuse and extend the existing YAML parser logic** already available for Markdown metadata handling:  
  [getMarkdownMetadata.ts](https://github.com/aymericzip/intlayer/blob/main/packages/%40intlayer/core/src/transpiler/markdown/getMarkdownMetadata.ts)

- **Do not introduce external libraries** for YAML parsing. Stick to internal utilities for better maintainability and control.

- Ensure **centralized** YAML parsing logic under:

  - `@intlayer/core` package:  
    ➔ `/src/utils/`

- The **transpilation** of YAML declaration files into the Intlayer dictionary format should be developed in:

  - `@intlayer/chokidar` package:  
    ➔ [`@intlayer/chokidar/src/transpiler/declaration_file_to_dictionary/intlayer_dictionary/`](https://github.com/aymericzip/intlayer/blob/main/packages/%40intlayer/chokidar/src/transpiler/declaration_file_to_dictionary/intlayer_dictionary)

- **Fallback** should be correctly managed:
  - If a translation is missing in a per-locale YAML file, fallback to the default language (e.g., English). Same behaviour as other declaration file format wanted

---

## Related Future Tasks

- Allow the **Intlayer Visual Editor** to directly interact with YAML files (planned feature).
- Improve tooling to auto-generate YAML per-language files from default YAML files.
- Adapt CLI command to integrate YAML file languages 

---

## Feature Based on Community Feedback

This feature request is directly inspired by feedback from Intlayer users requesting **YAML support** for a more flexible and developer-friendly content workflow.

Would you also like me to prepare a **title and short description** in case you want to open this issue on GitHub right away? 🚀
